In [1]:
#Створіть одновимірний масив (вектор) з простими числами, не перевищуючи 70, та виведіть його значення.

# Функція для генерації списку простих чисел менше або рівних заданому ліміту
def generate_primes(limit):
    primes = []
    for num in range(2, limit + 1):
        is_prime = True
        for i in range(2, int(num**0.5) + 1):
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(num)
    return primes

# Генерація простих чисел, що не перевищують 70
prime_numbers = generate_primes(70)

# Виведення значень простих чисел
print(prime_numbers)


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67]


In [2]:
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратів перших натуральних чисел.
import numpy as np

# Розмір матриці
matrix_size = 3

# Створення двовимірного масиву 3x3 з квадратами перших натуральних чисел
squares_matrix = np.array([[i**2 for i in range(1, matrix_size + 1)] for j in range(matrix_size)])

# Виведення матриці
print(squares_matrix)


[[1 4 9]
 [1 4 9]
 [1 4 9]]


In [3]:
# Створіть масив розміром 5x5, заповніть його випадковими цілими числами від -10 до 10 та знайдіть максимальний елемент.

import numpy as np

# Встановлення розміру масиву
array_size = (5, 5)

# Генерація масиву 5x5 з випадковими цілими числами від -10 до 10
random_array = np.random.randint(-10, 11, size=array_size)

# Знаходження максимального елемента
max_element = np.max(random_array)

# Виведення масиву та максимального елемента
print("Масив:")
print(random_array)
print("Максимальний елемент:", max_element)


Масив:
[[ 3  4 -9 -2  5]
 [ 4 -5 -4  4 -3]
 [-5 10 10  7  9]
 [-8 -8 -2 -2  2]
 [ 2  5 -1 -7 -8]]
Максимальний елемент: 10


In [4]:
# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-рядок, 
# що містить максимальні елементи в кожному стовпці.
import numpy as np

# Створення масиву 4x4 з випадковими числами від 0 до 1
array = np.random.rand(4, 4)
print("Масив 4x4:")
print(array)

# Знаходження максимальних елементів у кожному стовпці
max_elements = np.max(array, axis=0)
print("Вектор-рядок з максимальними елементами в кожному стовпці:")
print(max_elements)


Масив 4x4:
[[0.57248885 0.37092386 0.45926538 0.51600754]
 [0.70450969 0.24718213 0.19454544 0.71283291]
 [0.30705455 0.23158038 0.19283076 0.6753662 ]
 [0.35165961 0.94742567 0.37633803 0.4693232 ]]
Вектор-рядок з максимальними елементами в кожному стовпці:
[0.70450969 0.94742567 0.45926538 0.71283291]


In [5]:
#  Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 
# та виконайте на них поелементні операції додавання, віднімання та множення.

import numpy as np

# Створення двох масивів розміром 7 з випадковими цілими числами від -10 до 10
array1 = np.random.randint(-10, 11, size=7)
array2 = np.random.randint(-10, 11, size=7)

print("Масив 1:")
print(array1)
print("Масив 2:")
print(array2)

# Поелементне додавання
addition = np.add(array1, array2)
print("Поелементне додавання:")
print(addition)

# Поелементне віднімання
subtraction = np.subtract(array1, array2)
print("Поелементне віднімання:")
print(subtraction)

# Поелементне множення
multiplication = np.multiply(array1, array2)
print("Поелементне множення:")
print(multiplication)


Масив 1:
[10 -4 -7  5 -1  6  5]
Масив 2:
[ 4  3  4 -3  8  3 10]
Поелементне додавання:
[14 -1 -3  2  7  9 15]
Поелементне віднімання:
[  6  -7 -11   8  -9   3  -5]
Поелементне множення:
[ 40 -12 -28 -15  -8  18  50]


In [6]:
# Створіть дві матриці 4x4, заповніть їх довільними цілими числами від -10 до 10 та знайдіть їх добуток.

import numpy as np

# Створення двох матриць 4x4 з випадковими цілими числами від -10 до 10
matrix1 = np.random.randint(-10, 11, size=(4, 4))
matrix2 = np.random.randint(-10, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

# Знаходження добутку двох матриць
product = np.dot(matrix1, matrix2)
print("Добуток матриць:")
print(product)



Матриця 1:
[[-8  1 -2 -9]
 [ 6 -9 -3  5]
 [ 1 -7  1  5]
 [-3  6 -2 10]]
Матриця 2:
[[ 3  5  8 -6]
 [ 8 -4  5  4]
 [-9 -7 -7 -9]
 [ 9 -5 -8 -9]]
Добуток матриць:
[[-79  15  27 151]
 [ 18  62 -16 -90]
 [-17   1 -74 -88]
 [147 -75 -60 -30]]


In [7]:
 #Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та перемножте їх між собою.

import numpy as np

# Створення матриці 4x2 з випадковими цілими числами від 1 до 3
matrix1 = np.random.randint(1, 4, size=(4, 2))
print("Матриця 1:")
print(matrix1)

# Створення матриці 2x2 з випадковими цілими числами від 1 до 3
matrix2 = np.random.randint(1, 4, size=(2, 2))
print("Матриця 2:")
print(matrix2)

# Множення матриць
product = np.dot(matrix1, matrix2)
print("Добуток матриць:")
print(product)


Матриця 1:
[[2 1]
 [3 2]
 [2 3]
 [1 1]]
Матриця 2:
[[2 1]
 [2 3]]
Добуток матриць:
[[ 6  5]
 [10  9]
 [10 11]
 [ 4  4]]


In [8]:
# Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.
import numpy as np

# Створення матриці 2x2 з випадковими цілими числами від 1 до 7
matrix = np.random.randint(1, 8, size=(2, 2))
print("Матриця 2x2:")
print(matrix)

# Обчислення оберненої матриці
inverse_matrix = np.linalg.inv(matrix)
print("Обернена матриця:")
print(inverse_matrix)


Матриця 2x2:
[[5 2]
 [2 7]]
Обернена матриця:
[[ 0.22580645 -0.06451613]
 [-0.06451613  0.16129032]]


In [9]:
# Створіть матрицю розміром 3x5, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її.

import numpy as np

# Створення матриці 3x5 з випадковими цілими числами від 0 до 1
matrix = np.random.randint(0, 2, size=(3, 5))
print("Матриця 3x5:")
print(matrix)

# Транспонування матриці
transposed_matrix = np.transpose(matrix)
print("Транспонована матриця:")
print(transposed_matrix)


Матриця 3x5:
[[0 1 0 0 1]
 [1 1 0 0 1]
 [0 1 1 0 1]]
Транспонована матриця:
[[0 1 0]
 [1 1 1]
 [0 0 1]
 [0 0 0]
 [1 1 1]]


In [10]:
# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, 
# а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import numpy as np

# Створення матриці 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 4)
print("Матриця 3x4:")
print(matrix)

# Створення вектора 4x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(4, 1))
print("Вектор 4x1:")
print(vector)

# Множення матриці на вектор
product = np.dot(matrix, vector)
print("Добуток матриці на вектор:")
print(product)


Матриця 3x4:
[[0.52197884 0.72455203 0.26533289 0.35212949]
 [0.26287976 0.69901087 0.01687279 0.17064597]
 [0.46525621 0.60137911 0.68570732 0.47812605]]
Вектор 4x1:
[[3]
 [6]
 [7]
 [3]]
Добуток матриці на вектор:
[[ 8.82696746]
 [ 5.61275192]
 [11.23837269]]


In [11]:
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними 
# числами від 0 до 1, і знайдіть суму елементів матриці, які менше за відповідний елемент вектору.

import numpy as np

# Створення матриці 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)
print("Матриця 2x3:")
print(matrix)

# Створення вектора 3x1 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(3, 1)
print("Вектор 3x1:")
print(vector)

# Знаходження суми елементів матриці, які менше за відповідний елемент вектору
sum_elements = np.sum(matrix < vector.T, axis=1)
print("Сума елементів матриці, які менше за відповідний елемент вектору:")
print(sum_elements)


Матриця 2x3:
[[0.59218779 0.36201939 0.58553254]
 [0.73924421 0.16481429 0.66515507]]
Вектор 3x1:
[[0.5344906 ]
 [0.2665204 ]
 [0.91380111]]
Сума елементів матриці, які менше за відповідний елемент вектору:
[1 2]


In [12]:
# Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.
import numpy as np

# Створення двох матриць 8x8 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(8, 8))
matrix2 = np.random.randint(1, 11, size=(8, 8))

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

# Знаходження суми двох матриць
sum_matrix = np.add(matrix1, matrix2)
print("Сума матриць:")
print(sum_matrix)


Матриця 1:
[[ 9  6  1  1  1  8  4  6]
 [ 7 10  5  4 10  6  9  7]
 [10  4  7 10  7  8  1  1]
 [ 6  7 10  6  4  1  2  9]
 [ 6  5  6  1  2  5  6  2]
 [ 5  3  6  9 10  4  2  1]
 [ 5  8 10  8  7  8  4  9]
 [ 5  7  2  4  2  9  4 10]]
Матриця 2:
[[ 4  5 10  2  6  4  2  8]
 [ 3  3 10  6  3  8  9 10]
 [ 7  2  1  9  7  7 10  1]
 [ 8  3  2  9  4  3  9  5]
 [ 9  4  2  9  8  6  3  2]
 [ 4  4  3  3  9  5  7  6]
 [ 4  3  7  3  1  9  3  3]
 [ 2  4  5  4  8  6  6  4]]
Сума матриць:
[[13 11 11  3  7 12  6 14]
 [10 13 15 10 13 14 18 17]
 [17  6  8 19 14 15 11  2]
 [14 10 12 15  8  4 11 14]
 [15  9  8 10 10 11  9  4]
 [ 9  7  9 12 19  9  9  7]
 [ 9 11 17 11  8 17  7 12]
 [ 7 11  7  8 10 15 10 14]]


In [13]:
# Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть добуток їх елементів.
import numpy as np

# Створення двох матриць 3x3 з випадковими дійсними числами від -1 до 1
matrix1 = 2 * np.random.rand(3, 3) - 1
matrix2 = 2 * np.random.rand(3, 3) - 1

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

# Поелементне множення матриць
elementwise_product = np.multiply(matrix1, matrix2)
print("Добуток елементів матриць:")
print(elementwise_product)


Матриця 1:
[[ 0.9748496   0.13422097 -0.68347184]
 [ 0.32537285 -0.34937993  0.66420682]
 [-0.2760447   0.11226118 -0.00880992]]
Матриця 2:
[[ 0.03185743 -0.82011293  0.14957227]
 [ 0.91696186 -0.60555383 -0.85100861]
 [ 0.46526033 -0.82061023  0.44774067]]
Добуток елементів матриць:
[[ 0.0310562  -0.11007635 -0.10222843]
 [ 0.2983545   0.21156835 -0.56524572]
 [-0.12843265 -0.09212267 -0.00394456]]


In [14]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та знайдіть добуток елементів матриці, 
# які більше за їх середнє арифметичне значення.
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами від -5 до 5
matrix = 10 * np.random.rand(3, 3) - 5
print("Матриця 3x3:")
print(matrix)

# Обчислення середнього арифметичного значення елементів матриці
mean_value = np.mean(matrix)
print("Середнє арифметичне значення елементів матриці:")
print(mean_value)

# Знаходження елементів, які більше за середнє арифметичне значення
greater_than_mean = matrix[matrix > mean_value]
print("Елементи, які більше за середнє арифметичне значення:")
print(greater_than_mean)

# Обчислення добутку цих елементів
product_of_elements = np.prod(greater_than_mean)
print("Добуток елементів, які більше за середнє арифметичне значення:")
print(product_of_elements)


Матриця 3x3:
[[ 4.92053246  1.44440218 -3.58705413]
 [ 4.39270182 -4.32937315  2.71654948]
 [ 4.38722264  0.38988194 -2.32895276]]
Середнє арифметичне значення елементів матриці:
0.889545609896063
Елементи, які більше за середнє арифметичне значення:
[4.92053246 1.44440218 4.39270182 2.71654948 4.38722264]
Добуток елементів, які більше за середнє арифметичне значення:
372.0825098337077


In [15]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, 
# що містить найбільше за модулем ціле значення в кожному рядку матриці.
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами від -0.5 до 0.5
matrix = np.random.rand(3, 3) - 0.5
print("Матриця 3x3:")
print(matrix)

# Знаходження найбільшого за модулем цілого значення в кожному рядку
max_abs_int_vector = np.array([int(np.round(np.max(np.abs(row)))) for row in matrix])
print("Вектор-стовпчик з найбільшими за модулем цілими значеннями в кожному рядку:")
print(max_abs_int_vector)


Матриця 3x3:
[[-0.16441806  0.48607294  0.04726485]
 [ 0.47592183  0.25159255 -0.05901229]
 [ 0.0112678  -0.08281685  0.31874623]]
Вектор-стовпчик з найбільшими за модулем цілими значеннями в кожному рядку:
[0 0 0]
